config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  resources :users, only: :show #マイページへ
  resources :products do
    resources :reviews
  end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
  belongs_to :user, optional: true
  has_one_attached :avatar
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :products
  has_many :reviewed_products, through: :reviews, source: :product
 # has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# def after_sign_in_path_for(resource)
#   if current_user.admin?
#     products_path
#   else
#     root_path
#   end
# end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

# before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new #予め定義されているnewメソッド
  end

  def create
    product = Product.create(product_params)
    redirect_to products_path #rake routesで確認、prefixに_pathをつける
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy #予め定義されているdestroyメソッド
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
  end

  private

  def product_params
      params.require(:product).permit(:name, :recommendation, :price, :avatar).merge(user_id: current_user.id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :authenticate_user!, :except => [:index]

  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    review = Review.create(create_params)
    redirect_to product_path(review.product_id)
  end

  private
  def create_params
    params.require(:review).permit(:comment, :rate,).merge(product_id: params[:product_id],user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @products = current_user.reviewed_products.uniq
     @reviews = current_user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cafeteria</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
 </head>
 <body>
  <header>
   <nav class="#304ffe indigo accent-4">
    <div class="nav-wrapper">
     <a href="/" class="brand-logo p_title"> ⭐️カフェテリア⭐️</a>
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="fas fa-bars"></i></a>
     <!--<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>-->
     <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
       <div class="user_nav grid-6">
       <% if current_user.id == 1 %>
        <li><%= link_to "商品登録", new_product_path, class: 'get' %></li>
       <% end %>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
       </div>
      <% else %>
      <div class="grid-6">
       <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
       <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
      </div>
      <% end %>
     </ul>
     <ul class="side-nav" id="mobile-demo">
      <% if user_signed_in? %>
       <% if current_user.id == 1 %>
        <li><%= link_to "商品登録", new_product_path, class: 'get' %></li>
       <% end %>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
       <% else %>
        <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
        <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
      <% end %>
     </ul>
    </div>
   </nav>
  </header>
  <%= yield %>
  <footer>
  </footer>
 </body>
</html>

app/views/products/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">商品一覧へ戻る</a>
  </div>
</div>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>

<div style="margin: 8px 0">
  <%= f.label :商品名, style: { 'margin-right' => 8 } %>
  <%= f.text_field :name, placeholder: 'ここに記入', value: @product.name %>
</div>

<div style="margin: 8px 0">
  <%= f.label :商品概要, style: { 'margin-right' => 8 } %>
  <%= f.text_area :recommendation, placeholder: 'ここに記入', style: 'width: 100%;height: 300px;', value: @product.recommendation %>
</div>

<div style="margin: 8px 0">
  <%= f.label :価格, style: { 'margin-right' => 8 } %>
  <%= f.number_field :price, placeholder: 'ここに記入' %>
</div>

<div class="field">
  <%= f.label :商品画像, style: { 'margin-right' => 8 } %>
  <%= f.file_field :avatar %>
</div>

<div class="row">
  <div class="col10 push1">
    <%= button_tag type: "submit", class: "btn btn--block" do %>
    編集を終了する<i class="icon-arrow-right"></i>
    <% end %>
  </div>
</div>

<% end %>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col s12 m6 l4">

    <a href="/products/<%= product.id %>" class="top-a">

      <div class="card">

        <div class="card-image">
          <!-- <img src="images/sample-1.jpg"> -->
<% if product.avatar.attached? %>
          <%= image_tag product.avatar,class: "avatar" %>
<% end %>
        </div>

        <div class="card-content">
          <span class="card-title"><%= product.name %></span>
          <p>オススメ：<%= product.recommendation %></p>
          <p>価格：<%= product.price %>円</p>
          <% if product.reviews.present? %>
          <p>評価：<%= product.reviews.average(:rate).round(1) %></p>

        <div class="star-rating">
            <div class="star-rating-front" style="width: <%= product.reviews.average(:rate).round(1)*20; %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
        </div>
          <% else  %>

          <p>評価：未登録</p>

        <div class="star-rating">
            <div class="star-rating-front" style="width: 0">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
        </div>

                  <% end %>

        <% if user_signed_in? %>
        <% if current_user.id == 1 %>
        <div class="edit_btn center">
        <div class="btn btn_text">
            <%= link_to '編集', edit_product_path(product.id), method: :get %>
        </div>
        <div class="btn btn_text">
            <%= link_to '削除', "/products/#{product.id}", method: :delete, data: {confirm: "本当に削除しますか？"}%>
        </div>
      </div>
        <% else %>
        <br>
<!--         <div class="row">
          <div class="col10 push1"> -->
            <%= link_to 'レビューする', new_product_review_path(product.id), method: :get %>
<!--           </div>
        </div> -->
        <% end %>
        <% end %>

        </div>
      </div>

    </a>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="form_wrap">
<%= form_for @product do |f| %>

<div class="input-field">
  <%= f.label :商品名 %>
  <%= f.text_field :name %>
</div>

<div class="input-field">
  <%= f.label :商品概要 %>
  <%= f.text_area :recommendation, style: 'width: 100%;height: 300px;' %>
</div>

<div class="input-field">
  <%= f.label :価格 %>
  <%= f.number_field :price %>
</div>

<div class="field">
  <%= f.label :商品画像, style: { 'margin-right' => 8 } %>
  <%= f.file_field :avatar %>
</div>

<div class="row">
  <div class="col10 center">
    <%= button_tag type: "submit", class: "btn btn--block" do %>
    登録する<i class="icon-arrow-right"></i>
    <% end %>
  </div>
</div>
<% end %>
</div>

app/views/products/show.html.erb
<div class="body_container">
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-image">
        <!-- <img src="images/sample-1.jpg"> -->
<% if @product.avatar.attached? %>
        <%= image_tag @product.avatar %>
<% end %>
      </div>
      <div class="card-content">
        <span class="card-title"><%= @product.name %></span>
        <p><%= @product.recommendation %></p>
        <p>価格：<%= @product.price %>円</p>
        <% if @reviews.present? %>
        <p>評価：<%= @reviews.average(:rate).round(1) %></p>
        <% end %>
        <div class="row">
          <div class="col10 push1">
            <%= link_to 'レビューする', new_product_review_path(@product.id), method: :get %>
          </div>
        </div>
      </div>
    </div>
    <% if @reviews.present? %>
<p class="center">レビュー一覧</p>
<% @reviews.each do |review| %>
<p>評価：<%= review.rate %> | <%= review.comment %></p>
<hr>
<% end %>
<% end %>
  </div>
</div>
</div>

app/views/products/update.html.erb
<div class="form_wrap center">
  <p>更新が完了しました。</p>
    <a class="btn" href="/">商品一覧へ戻る</a>
  </div>

app/views/reviews/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col s12 m6 l3">
    <!--<a href="/products/<%= product.id %>/reviews/new">-->

      <div class="card">

        <div class="card-image">
          <!-- <img src="images/sample-1.jpg"> -->
          <%= image_tag product.avatar %>
        </div>

        <div class="card-content">
          <span class="card-title"><%= product.name %></span>
          <p><%= product.recommendation %></p>
          <p><%= product.price %></p>
        </div>

        <div class="row">
          <div class="col10 push1">
            <%= link_to 'レビューする', new_product_review_path(product.id), method: :get %>
          </div>
        </div>

      </div>

    <!--</a>-->

    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="body_container">
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-image">
        <!-- <img src="images/sample-1.jpg"> -->
        <%= image_tag @product.avatar %>
      </div>
      <div class="card-content">
        <span class="card-title"><%= @product.name %></span>
        <p><%= @product.recommendation %></p>
        <p><%= @product.price %></p>
      </div>
    </div>

<%= form_for [@product, @review] do |f| %>

<div style="margin: 8px 0">
  <%= f.label :評価, style: { 'margin-right' => 8 } %>
  <%= f.number_field :rate, placeholder: '評価', value: 1, max: 5, min: 1, html: { class: "search__query", style: 'text-align: right;' } %>
</div>

<div style="margin: 8px 0">
  <%= f.label :商品概要, style: { 'margin-right' => 8 } %>
  <%= f.text_area :comment, placeholder: 'ここに記入', style: 'width: 100%;height: 150px;' %>
</div>

<div class="row">
  <div class="col10 push1">
    <%= button_tag type: "submit", class: "btn btn--block" do %>
    投稿する<i class="icon-arrow-right"></i>
    <% end %>
  </div>
</div>

<% end %>

  </div>
</div>
</div>

app/views/users/##show.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col s12 m6 l3">

    <a href="/products/<%= product.id %>" class="top-a">

      <div class="card">

        <div class="card-image">
          <!-- <img src="images/sample-1.jpg"> -->
          <%= image_tag product.avatar,class: "avatar" %>
        </div>

        <div class="card-content">
          <span class="card-title"><%= product.name %></span>
          <p>オススメ：<%= product.recommendation %></p>
          <p>価格：<%= product.price %>円</p>
          <p>評価：<%= product.reviews.average(:rate).round(1) %></p>

        <div class="star-rating">
            <div class="star-rating-front" style="width: <%= product.reviews.average(:rate).round(1)*20; %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
        </div>

        <% if user_signed_in? %>
        <% if current_user.id == 1 %>
        <div class="row">
          <div class="col10 push1">
            <%= link_to '編集', edit_product_path(product.id), method: :get %>
          </div>
        </div>
        <div class="row">
          <div class="col10 push1">
            <%= link_to '削除', "/products/#{product.id}", method: :delete, data: {confirm: "本当に削除しますか？"}%>
          </div>
        </div>
        <% else %>
        <br>
<!--         <div class="row">
          <div class="col10 push1"> -->
            <%= link_to 'レビューする', new_product_review_path(product.id), method: :get %>
<!--           </div>
        </div> -->
        <% end %>
        <% end %>

        </div>
      </div>

    </a>
    </div>
  <% end %>
</div>

            <% current_user.reviews.each do |review| %>
            <p><%= review.comment %> <%= review.updated_at %></p>
            <% end %>

app/views/users/show.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col s12 m6 l4">

    <a href="/products/<%= product.id %>" class="top-a">

      <div class="card">

        <div class="card-image">
          <!-- <img src="images/sample-1.jpg"> -->
<% if product.avatar.attached? %>
          <%= image_tag product.avatar,class: "avatar" %>
<% end %>
        </div>

        <div class="card-content">
          <span class="card-title"><%= product.name %></span>
          <p>オススメ：<%= product.recommendation %></p>
          <p>価格：<%= product.price %>円</p>
          <% if product.reviews.present? %>
          <p>評価：<%= product.reviews.average(:rate).round(1) %></p>

        <div class="star-rating">
            <div class="star-rating-front" style="width: <%= product.reviews.average(:rate).round(1)*20; %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
        </div>
          <% else  %>

          <p>評価：未登録</p>

        <div class="star-rating">
            <div class="star-rating-front" style="width: 0">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
        </div>

                  <% end %>


        <br>
<!--         <div class="row">
          <div class="col10 push1"> -->
            <%= link_to 'レビューする', new_product_review_path(product.id), method: :get %>
<!--           </div>
        </div> -->



        </div>
      </div>

    </a>
    </div>
  <% end %>
</div>



<!-- <div class="row">

  <% @products.each do |product| %>
    <div class="col s12 m6 l4">

      <div class="card">

        <div class="card-image">
          <%= image_tag product.avatar %>
        </div>

        <div class="card-content">
          <span class="card-title"><%= product.name %></span>

            <% @reviews.each do |review| %>
            <p><%= review.comment %> <%= review.updated_at %></p>
            <% end %>
        </div>

      </div>

    </div>
  <% end %>
</div>


 -->